In [2]:
#convert the below list into numpy array then display the array 
#then display the array then display the first and last index and then multiply each element by 2 
#and display the result   
#input: my_list=[1,2,3,4,5]   output: first element:1  last element:5   array after doubling each element:[2,4,6,8,10]
import numpy as np
my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)
print("NumPy Array:")
print(my_array)
first_element = my_array[0]
last_element = my_array[-1]
print(f"First element: {first_element}")
print(f"Last element: {last_element}")
doubled_array = my_array * 2
print("Array after doubling each element:")
print(doubled_array)


NumPy Array:
[1 2 3 4 5]
First element: 1
Last element: 5
Array after doubling each element:
[ 2  4  6  8 10]


In [3]:
#write a numpy program to create an array of 10 zeros,10 ones , and 10 fives.    
#sample output:    an array of 10 zeros: [0,0,0,0,0,0,0,0,0,0]     an array of 10 ones: [1,1,1,1,1,1,1,1,1,1]   an array of 10 fives:   [5,5,5,5,5,5,5,5,5,5]
import numpy as np
zeros_array = np.zeros(10, dtype=int)
print("An array of 10 zeros:")
print(zeros_array)
ones_array = np.ones(10, dtype=int)
print("\nAn array of 10 ones:")
print(ones_array)
fives_array = np.full(10, 5, dtype=int)
print("\nAn array of 10 fives:")
print(fives_array)


An array of 10 zeros:
[0 0 0 0 0 0 0 0 0 0]

An array of 10 ones:
[1 1 1 1 1 1 1 1 1 1]

An array of 10 fives:
[5 5 5 5 5 5 5 5 5 5]


In [4]:
#write a numpy program to create a 3*3 matrix with values ranging from 2 to 10 
import numpy as np
values = np.arange(2, 11)
matrix = values.reshape(3, 3)
print("3x3 Matrix with values ranging from 2 to 10:")
print(matrix)

3x3 Matrix with values ranging from 2 to 10:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
