In [2]:
#convert the below list into numpy array then display the array 
#then display the array then display the first and last index and then multiply each element by 2 
#and display the result   
#input: my_list=[1,2,3,4,5]   output: first element:1  last element:5   array after doubling each element:[2,4,6,8,10]
import numpy as np
my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)
print("NumPy Array:")
print(my_array)
first_element = my_array[0]
last_element = my_array[-1]
print(f"First element: {first_element}")
print(f"Last element: {last_element}")
doubled_array = my_array * 2
print("Array after doubling each element:")
print(doubled_array)


NumPy Array:
[1 2 3 4 5]
First element: 1
Last element: 5
Array after doubling each element:
[ 2  4  6  8 10]


In [3]:
#write a numpy program to create an array of 10 zeros,10 ones , and 10 fives.    
#sample output:    an array of 10 zeros: [0,0,0,0,0,0,0,0,0,0]     an array of 10 ones: [1,1,1,1,1,1,1,1,1,1]   an array of 10 fives:   [5,5,5,5,5,5,5,5,5,5]
import numpy as np
zeros_array = np.zeros(10, dtype=int)
print("An array of 10 zeros:")
print(zeros_array)
ones_array = np.ones(10, dtype=int)
print("\nAn array of 10 ones:")
print(ones_array)
fives_array = np.full(10, 5, dtype=int)
print("\nAn array of 10 fives:")
print(fives_array)


An array of 10 zeros:
[0 0 0 0 0 0 0 0 0 0]

An array of 10 ones:
[1 1 1 1 1 1 1 1 1 1]

An array of 10 fives:
[5 5 5 5 5 5 5 5 5 5]


In [4]:
#write a numpy program to create a 3*3 matrix with values ranging from 2 to 10 
import numpy as np
values = np.arange(2, 11)
matrix = values.reshape(3, 3)
print("3x3 Matrix with values ranging from 2 to 10:")
print(matrix)

3x3 Matrix with values ranging from 2 to 10:
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [8]:
#calculate the total revenue generated by two product categories in a store
#input:  category1_revenue=np.array([500,600,700,650)]
#category2_revenue=np.array([450,700,800,600])
#output: total revenue:[950,1300,1500,1150]
import numpy as np
category1_revenue = np.array([500, 600, 700, 650])
category2_revenue = np.array([450, 700, 800, 600])
total_revenue = category1_revenue + category2_revenue
print(f"Total revenue : {total_revenue}")


Total revenue : [ 950 1300 1500 1250]


In [10]:
#calculate the profit made by a company   
#input:  revenue=np.array([10000,12000,11000,10500])        
#expenses=np.array([4000,5000,4500,4800])    
#output:  profit=[6000,7000,8500,5700]
import numpy as np
revenue = np.array([10000, 12000, 11000, 10500])
expenses = np.array([4000, 5000, 4500, 4800])
profit = revenue - expenses
print(f"Profit: {profit}")

Profit: [6000 7000 6500 5700]


In [12]:
#determine which product in a store are out of stock(quantity is 0)    
#input: inventory=np.array([10,0,5,0,20,0])   
#output:  out of stock products:[0 0 0]
import numpy as np
inventory = np.array([10, 0, 5, 0, 20, 0])
out_of_stock = inventory[inventory == 0]
print("Out of stock products:", out_of_stock)

Out of stock products: [0 0 0]


In [13]:
#calculate the total cost of items in a shopping cart, considering the quantity and price per item         
#input: quantity=np.array([2,3,4,1])  
#price_per_item=np.array([10.0,5.0,8.0,12.0])  
#output: total cost of items:[20,15,32,12]
import numpy as np
quantity = np.array([2, 3, 4, 1])
price_per_item = np.array([10.0, 5.0, 8.0, 12.0])
total_cost = quantity * price_per_item
print("Total cost of items:", total_cost)

Total cost of items: [20. 15. 32. 12.]
